### ISSUE TITLE
element semantics when element has begin>end timing information.

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#312] opened 2017-01-23 12:41 UTC
Figure out what to do.

**Comment by nigelmegitt** [comment] 2017-01-23 12:54
See also the spec issue https://git.ebu.io/ebutt/ebutt-part-3/issues/137

In general elements whose `begin>=end` are never active so they do not need to be presented or considered for processing - this is SMIL semantic stuff, so not explicit in the Part 3 spec.

However there is specific text in the Part 3 spec about how to calculate the _earliest computed begin_ and _latest computed end_ times in the documents, for the purpose of calculating the document resolved begin times. The proposal in the spec issue is to exclude any elements with both `begin` and `end` attributes present where `begin` is later than or equal to `end` from the algorithm for calculating those, so they do not produce odd behaviour.

The only thing we may need to watch out for here is midnight crossing, when trying to work out which is later. Or we could always consider that if `end<=begin` and timebase is clock then end must be the following day?

**Comment by nigelmegitt** [comment] 2017-01-27 17:25
This is actually a duplicate of #241 I believe.

**Comment by nigelmegitt** [comment] 2017-02-01 15:28
Agreed today to exclude elements where begin is later than end from calculation of earliest computed begin time and latest computed end time.

**Comment by nigelmegitt** [comment] 2017-04-01 00:42
I'm pretty sure we implemented this, not sure of myself now though... We closed #241 as a duplicate of this one. I'm expecting the code that does this to be in `bindings/validation/timing.py` but I can't actually see it...

Digging a bit deeper, it seems that a test for `self.end<=self.begin` in `content.py` in the method `SubtitleContentContainer.contains_subtitles(self)`, returning `false` always if the element ends before it begins might work. That would cause `is_empty()` to return `true` which via the `ContentContainerMixin._assert_empty_container()` method would raise a `DiscardElement`. That in turn gets caught in `documents/ebutt3_segmentation.py`.

This is the beginning of a plan, but I'd like to validate it with someone who knows what they are doing, and not at this time of the morning!

**Comment by nigelmegitt** [comment] 2017-05-15 15:59
@EyalLavi no, I haven't looked at this any more since I posted https://github.com/ebu/ebu-tt-live-toolkit/issues/312#issuecomment-290879736

**Comment by nigelmegitt** [comment] 2017-05-23 16:51
Reminder, the spec text is:

> The “earliest computed begin time” is defined as the earlier of a) the earliest computed begin time of any leaf element in the document and b) the earliest computed time corresponding to a specified begin attribute value on an element that either has no end attribute value or has an end attribute value that is later than the begin attribute value. Note that in the case that a root to leaf path contains elements all of which omit a begin attribute value this evaluates to the value zero on the document’s timebase.
>
> The “latest computed end time” is defined as the latest computed end time corresponding to a specified end attribute value on an element that either has no specified begin attribute value or has an end attribute value that is later than the begin attribute value. Note that in the case that a root to leaf path contains elements all of which omit an end attribute this evaluates to the [SMIL] term "undefined", i.e. the latest computed end time is not determined, and is effectively infinite for comparison purposes.

This means that a BDD that includes elements with both `begin` and `end` attributes, whose `begin >= end` should exclude those elements when calculating the computed begin and end times.

**Closed** 2017-05-24 17:07 UTC
Labels: pending PR merge
