### ISSUE TITLE
Implement R107: Discard document with already seen pair of sequence identifier and number

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#297] opened 2016-12-16 12:18 UTC
R107: Processors shall discard documents whose pair of `ebuttp:sequenceIdentifier` and `ebuttp:sequenceNumber` are identical to those in a previously received document. The availability time of the document shall not be changed due to such a discard.

TBC: do we want to issue a warning as per this:

>processors may issue a warning if the two documents are not byte-wise identical.

**Comment by nigelmegitt** [comment] 2016-12-16 12:21
Yes I think we do want to issue the warning.

**Comment by kozmaz87** [comment] 2017-01-26 14:07
This means we need a function in the AbstractConsumerNode class to give us the tracking functionality and it needs to be called from process_document. If the process_document function does not call this the behaviour will not be there.

**Comment by kozmaz87** [comment] 2017-01-30 17:18
Duplicate of #258 which caters for above requirements. The solution ended up being tied to sequence object. The sequence object can tell you when it has a document and refuse adding in a document and raises an Exception. the node code can handle this and make further decisions.

**Closed by kozmaz87** 2017-01-30 17:18 UTC
