### ISSUE TITLE
Timebase semantic testing

### ISSUE THREAD

**Issue by gilbrechbuhler** [ebu/ebu-tt-live-toolkit#7] opened 2016-06-30 15:15 UTC
Test semantic validation on timebase rules :

```
Start point of a temporal interval associated with a tt:body element.
If the timebase is "smpte" the type shall be ebuttdt:smpteTimingType .
If the timebase is "media" the type shall be ebuttdt:mediaTimingType .
If the timebase is "media" the time expression should be the offset from a syncbase of "00:00:00.0".
If the timebase is "clock" the type shall be ebuttdt:clockTimingType .
```

**Comment by gilbrechbuhler** [comment] 2016-06-30 15:17
@kozmaz87 @frans-ebu @nigelmegitt 

Next tests I will write, of course for now they will be skipped as the semantic validation is not implemented. But I think those are among the most important tests to write.

**Comment by nigelmegitt** [comment] 2016-06-30 15:33
Okay, sounds good to me. For me the important thing for us to get to is that we can validate the document activation rules in the context of a sequence of documents - spec section §2.3.1. This is a step on the way to getting there.

**Comment by gilbrechbuhler** [comment] 2016-06-30 15:34
Yeah 2.3.1 will be a big part to test, however for now, as we do not have a presentation node or anything else that actually use the timing, it is a bit hard to test. Unless I am missing something, which is possible too.

**Comment by nigelmegitt** [comment] 2016-06-30 15:39
In my mind we don't actually need to present the output to verify the timing, we just need to write out a simulation of the events that would occur during playback, i.e. a timeline with the text that would appear at each time, which gets modified as new documents become available. This can be a text output to stdout for all I care, but at least that way it is reproducible.

Also, @kozmaz87 and I have discussed the idea of having a sequence of documents stored on a file system that can be processed immediately, with a manifest file that lists a set of pairs of document (sequence number) and availability time. By using different manifest files we can test the logic for different availability time scenarios without having to update a whole bunch of EBU-TT files every time, and without having to wait for the real elapsed time to happen.

**Comment by gilbrechbuhler** [comment] 2016-07-01 10:16
I'm facing a little confusion here, from tech 3370 (Annex A. p.56) :
```
<ebuttdt:mediaTimingType>
: <full-clock-value>
| <timecount-value>

<ebuttdt:clockTimingType>
: <full-clock-value>
| <timecount-value>

<full-clock-value>
: <hh> ":" <mm> ":" <ss> ("." <digit>+)?

<timecount-value>
: <digit>+ ("." <digit>+)? <metric>

<hh> | <mm> | <ss> | <ff>
: <digit> <digit>
```
Where in the XSD (ebutt_datatypes.xsd) I can see :
```
<xs:simpleType name="clockTimingType">
		<xs:union memberTypes="ebuttdt:limitedClockTimingType ebuttdt:timecountTimingType"/>
	</xs:simpleType>
	<xs:simpleType name="mediaTimingType">
		<xs:union memberTypes="ebuttdt:timecountTimingType ebuttdt:fullClockTimingType"/>
	</xs:simpleType>
	<xs:simpleType name="timecountTimingType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]+(\.[0-9]+)?(h|m|s|ms)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="limitedClockTimingType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9][0-9]:[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="fullClockTimingType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9][0-9]+:[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?"/>
		</xs:restriction>
</xs:simpleType>
```
In the XSD file, there is the type limitedClockTimingType which does not appear in tech 3370. The difference between fullClockTimingType and limitedClockTimingType is that 125:00:00.0 is allowed by the fullClock but not by the limitedClock. Also the definition in tech 3370 is clearly less restrictive than the definition in the XSD.

Which version should be trusted here ?

**Comment by nigelmegitt** [comment] 2016-07-01 11:18
3370 has a problem here, which is inherited from Part 1: the definitions of media time expressions and clock time expressions are supposed to be different but it's written in a really unclear way. Media times can have an unlimited number of digits in hours, whereas clock times must have 2 digits. The XSD is correctly requiring this _despite_ the spec...

**Comment by gilbrechbuhler** [comment] 2016-07-01 14:06
So the work is in the branch timebase_semantic_testing. I do not make a pull request yet because I'd like to polish it a bit better and maybe find more cases to test. But you are welcome to take a look at the branch already if you want.

**Comment by nigelmegitt** [comment] 2016-07-01 14:13
Looks like a good start. Now I can see more examples I like the general approach more and more - the way of describing the test and then templating with example values is really powerful and also readable.

**Comment by gilbrechbuhler** [comment] 2016-07-04 09:13
Pull request : #18

**Comment by nigelmegitt** [comment] 2016-07-04 09:15
FYI there's no need to link to the pull request explicitly if you mention the issue in the pull request description - github cross-links automatically, as you can see above.

**Comment by nigelmegitt** [comment] 2016-07-08 13:09
SMPTE tests moved into #52 so that we can resolve this more easily.

**Comment by nigelmegitt** [comment] 2016-07-08 13:31
PR merged, closing.

**Closed by nigelmegitt** 2016-07-08 13:31 UTC
Labels: awaiting review
