### ISSUE TITLE
Segmentation of document does not handle well body windowing cutting pieces out of document

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#241] opened 2016-10-12 14:59 UTC
The following document causes trouble

```
<?xml version="1.0" ?>
<tt:tt ebuttp:sequenceIdentifier="test" ebuttp:sequenceNumber="2" ttp:timeBase="media" tts:extent="800px 600px" xml:lang="en-GB" xmlns:ebuttm="urn:ebu:tt:metadata" xmlns:ebuttp="urn:ebu:tt:parameters" xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:xml="http://www.w3.org/XML/1998/namespace">
  <tt:head>
    <tt:metadata>
      <ebuttm:documentMetadata/>
    </tt:metadata>
    <tt:styling>
      <tt:style tts:fontSize="12px" xml:id="style1"/>
      <tt:style tts:fontSize="15px" xml:id="style2"/>
      <tt:style tts:color="red" tts:fontSize="12px" xml:id="style3"/>
    </tt:styling>
    <tt:layout>
      <tt:region style="style3" tts:extent="300px 150px" tts:origin="200px 450px" xml:id="region1"/>
    </tt:layout>
  </tt:head>
  <tt:body begin="00:00:06" end="00:00:05" style="style2">
    <tt:div region="region1" style="style1">
      <tt:p xml:id="ID005">


        <tt:span begin="00:00:01" end="00:00:02" xml:id="span1">Some example text...</tt:span>


        <tt:span begin="00:00:03" end="00:00:04" xml:id="span2">And another line</tt:span>


      </tt:p>
    </tt:div>
  </tt:body>
</tt:tt>
```

This document is -1 long. Validation should not allow this pass in my book. Let's discuss the validity of this case

**Comment by nigelmegitt** [comment] 2016-10-12 15:54
Actually this document is never active, since the resolved end time is before the resolved begin time regardless of the availability time here. In SMIL terms, as soon as the body becomes active it ends since the end time is already in the past.

This is syntactically valid but almost certainly unintended. The spec does not say it is invalid and does define the behaviour, but it would make sense to issue a validation warning. I do not think there is a bug here.

**Comment by kozmaz87** [comment] 2016-10-12 16:09
Ok but the segmentation needs to make sure it does not get surprised. Since this case slipped through validation it suggests that the system should set along with the valdation warning a flag to tell the segmenter to not even bother trying. It gets confused because it id not prepared to handle begin times before end times

**Comment by nigelmegitt** [comment] 2016-10-12 16:12
OK that's reasonable. I'm slightly surprised that the documents did not simply fall out of the timeline by the normal logic and that we need a special case here, but it certainly should not be getting confused.

**Comment by kozmaz87** [comment] 2016-10-12 16:14
I am also wondering the same thing.... how did this not get thrown out. It needs some investigation.

**Comment by nigelmegitt** [comment] 2016-12-14 18:07
Reviewing this, it looks like there is a bug after all, or there isn't and this can be closed. Either way, the question has been answered.

**Comment by nigelmegitt** [comment] 2017-01-27 17:26
There is also a spec issue - see #312 which should resolve this too.

**Comment by nigelmegitt** [comment] 2017-02-01 15:32
Closing as a duplicate of #312.

**Closed by nigelmegitt** 2017-02-01 15:32 UTC
Labels: bug, duplicate
